//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impacta.Testes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Impacta.Testes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RfcFunction Name=&quot;ZS_RFC_K033&quot;&gt;    &lt;Imports&gt;&lt;/Imports&gt;    &lt;Exports&gt;      &lt;ENTRADA Type=&quot;STRUCTURE&quot; Length=&quot;88&quot; Tag=&quot;&quot; Decimals=&quot;0&quot;&gt;        &lt;Structure FixedLength=&quot;88&quot; ABAPStructureName=&quot;ZSKS033ENT&quot;&gt;          &lt;CHNFE Type=&quot;CHAR&quot; Length=&quot;44&quot; Offset=&quot;0&quot; Decimals=&quot;0&quot; Tag=&quot;&quot;&gt;&lt;/CHNFE&gt;          &lt;CHNFE_RET Type=&quot;CHAR&quot; Length=&quot;44&quot; Offset=&quot;44&quot; Decimals=&quot;0&quot; Tag=&quot;&quot;&gt;&lt;/CHNFE_RET&gt;        &lt;/Structure&gt;        &lt;item&gt;          &lt;CHNFE&gt;&lt;/CHNFE&gt;          &lt;CHNFE_RET&gt;&lt;/CHNFE_RET&gt;        &lt;/item&gt;      &lt;/ENTRADA&gt;    &lt;/Exports&gt;    &lt;Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string K033Xml {
            get {
                return ResourceManager.GetString("K033Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RfcFunction Name=&quot;ZS_RFC_K033&quot;&gt;    &lt;Imports&gt;&lt;/Imports&gt;    &lt;Exports&gt;      &lt;ENTRADA Type=&quot;STRUCTURE&quot; Length=&quot;88&quot; Tag=&quot;&quot; Decimals=&quot;0&quot;&gt;        &lt;Structure FixedLength=&quot;88&quot; ABAPStructureName=&quot;ZSKS033ENT&quot;&gt;          &lt;CHNFE Type=&quot;CHAR&quot; Length=&quot;44&quot; Offset=&quot;0&quot; Decimals=&quot;0&quot; Tag=&quot;&quot;&gt;&lt;/CHNFE&gt;          &lt;CHNFE_RET Type=&quot;CHAR&quot; Length=&quot;44&quot; Offset=&quot;44&quot; Decimals=&quot;0&quot; Tag=&quot;&quot;&gt;&lt;/CHNFE_RET&gt;        &lt;/Structure&gt;        &lt;item&gt;          &lt;CHNFE&gt;&lt;/CHNFE&gt;          &lt;CHNFE_RET&gt;&lt;/CHNFE_RET&gt;        &lt;/item&gt;      &lt;/ENTRADA&gt;    &lt;/Exports&gt;    &lt;Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string K033XmlMalFormado {
            get {
                return ResourceManager.GetString("K033XmlMalFormado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;    &lt;xs:element name=&quot;RfcFunction&quot;&gt;      &lt;xs:complexType&gt;        &lt;xs:sequence&gt;          &lt;xs:element name=&quot;Imports&quot; /&gt;          &lt;xs:element name=&quot;Exports&quot;&gt;            &lt;xs:complexType&gt;              &lt;xs:sequence&gt;                &lt;xs:element name=&quot;ENTRADA&quot;&gt;                  &lt;xs:complexType&gt;                    &lt;xs:sequence&gt;                      &lt;xs:element name=&quot;Structure&quot;&gt;                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string K033Xsd {
            get {
                return ResourceManager.GetString("K033Xsd", resourceCulture);
            }
        }
    }
}
